/**
 * ════════════════════════════════════════════════════════════════════════════
 *  seed-demo.js — Patient 360°  |  Arabic / Damascus demo data seeder
 *  ──────────────────────────────────────────────────────────────────────────
 *  • Wipes every collection EXCEPT the 3 AI-analysis collections
 *    (knee_xray_analyses, drug_risk_checks, dental_caries_analyses) — untouched.
 *  • Re-seeds coherent Arabic, Damascus-centric demo data in correct dependency
 *    order, THROUGH the project Mongoose models, so:
 *      - passwords are bcrypt-hashed automatically (Account pre('validate'))
 *      - auto numbers (RX-/LAB-/DISP-/MED-) are generated by model hooks and the
 *        `counters` collection is populated automatically
 *      - every write satisfies the live $jsonSchema (same path the app uses)
 *  • Writes credentials.json + credentials.txt and prints a credentials table.
 *
 *  RUN (from the BACKEND ROOT — folder that has index.js and models/):
 *      node seed-demo.js
 *
 *  Reads MONGODB_URI from .env (fallback mongodb://localhost:27017/patient360).
 *  NOTE: persons/patients get NEW _ids, so the (untouched) AI-analysis docs keep
 *  pointing at OLD ids — expected, since you asked to leave the AI tables alone.
 * ════════════════════════════════════════════════════════════════════════════
 */
'use strict';

try { require('dotenv').config(); } catch (_) { /* dotenv optional */ }

const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/patient360';

// Register every model (same as the app: require('./models'))
require('./models');
const Person             = mongoose.model('Person');
const Children           = mongoose.model('Children');
const Account            = mongoose.model('Account');
const Admin              = mongoose.model('Admin');
const Doctor             = mongoose.model('Doctor');
const Dentist            = mongoose.model('Dentist');
const Pharmacist         = mongoose.model('Pharmacist');
const LabTechnician      = mongoose.model('LabTechnician');
const Hospital           = mongoose.model('Hospital');
const Pharmacy           = mongoose.model('Pharmacy');
const Laboratory         = mongoose.model('Laboratory');
const Medication         = mongoose.model('Medication');
const PharmacyInventory  = mongoose.model('PharmacyInventory');
const AvailabilitySlot   = mongoose.model('AvailabilitySlot');
const Appointment        = mongoose.model('Appointment');
const Visit              = mongoose.model('Visit');
const Prescription       = mongoose.model('Prescription');
const LabTest            = mongoose.model('LabTest');
const PharmacyDispensing = mongoose.model('PharmacyDispensing');
const Notification       = mongoose.model('Notification');
const Review             = mongoose.model('Review');
const EmergencyReport    = mongoose.model('EmergencyReport');
const Patient            = mongoose.model('Patient');
const Counter            = mongoose.model('Counter');

let DoctorRequest = null, FacilityRequest = null, AuditLog = null;
try { DoctorRequest   = mongoose.model('DoctorRequest'); }   catch (_) {}
try { FacilityRequest = mongoose.model('FacilityRequest'); } catch (_) {}
try { AuditLog        = mongoose.model('AuditLog'); }        catch (_) {}

// ── Helpers ─────────────────────────────────────────────────────────────────
const DAY = 24 * 60 * 60 * 1000;
const daysAgo   = (n) => new Date(Date.now() - n * DAY);
const daysAhead = (n) => new Date(Date.now() + n * DAY);
const ymd = (d = new Date()) =>
  `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;

const credentials = []; // { role, name, email, password }
async function createAccount({ email, password, roles, personId, childId, name, roleLabel }) {
  await Account.create({
    email,
    password, // plaintext → hashed by Account pre('validate')
    roles,
    ...(personId ? { personId } : {}),
    ...(childId ? { childId } : {}),
    isActive: true, isVerified: true, emailVerified: true, phoneVerified: true,
    language: 'ar', timezone: 'Asia/Damascus',
  });
  credentials.push({ role: roleLabel, name, email, password });
}

// ════════════════════════════════════════════════════════════════════════════
//  1) WIPE — everything except the 3 AI-analysis collections
// ════════════════════════════════════════════════════════════════════════════
async function wipe() {
  console.log('\n🧹 Clearing collections (AI-analysis collections are NOT touched)...');
  const toClear = [
    Notification, Review, PharmacyDispensing, LabTest, Prescription, Visit,
    Appointment, AvailabilitySlot, PharmacyInventory, EmergencyReport, Patient,
    Account, Admin, Doctor, Dentist, Pharmacist, LabTechnician,
    Medication, Hospital, Pharmacy, Laboratory, Children, Person, Counter,
  ];
  if (DoctorRequest)   toClear.push(DoctorRequest);
  if (FacilityRequest) toClear.push(FacilityRequest);
  if (AuditLog)        toClear.push(AuditLog);
  for (const M of toClear) {
    const r = await M.deleteMany({});
    console.log(`   • ${M.modelName.padEnd(20)} cleared ${r.deletedCount}`);
  }
}

// ════════════════════════════════════════════════════════════════════════════
//  2) SEED
// ════════════════════════════════════════════════════════════════════════════
async function seed() {
  // ── (a) PERSONS ───────────────────────────────────────────────────────────
  console.log('\n👤 persons...');
  const personDefs = [
    { key:'ahmad',  nid:'04001000001', f:'أحمد',   ab:'خالد',  l:'العلي',   m:'سميرة الحسن', g:'male',   dob:'1986-03-12', ph:'0944100001', city:'دمشق', dist:'المزة',    addr:'دمشق - المزة - شارع الجلاء - بناء 12', mar:'married', occ:'مهندس مدني' },
    { key:'layla',  nid:'04001000002', f:'ليلى',   ab:'محمود', l:'الحسن',   m:'فاطمة العمر', g:'female', dob:'1990-07-25', ph:'0944100002', city:'دمشق', dist:'المالكي',  addr:'دمشق - المالكي - شارع الرشيد - بناء 5',  mar:'married', occ:'مدرّسة' },
    { key:'omar',   nid:'04001000003', f:'عمر',    ab:'سامي',  l:'الخطيب',  m:'هدى الشامي',  g:'male',   dob:'1983-11-02', ph:'0944100003', city:'دمشق', dist:'كفرسوسة', addr:'دمشق - كفرسوسة - شارع الفردوس - بناء 8', mar:'married', occ:'محاسب' },
    { key:'rana',   nid:'04001000004', f:'رنا',    ab:'فادي',  l:'الشامي',  m:'ليلى الديب',  g:'female', dob:'1995-01-18', ph:'0944100004', city:'دمشق', dist:'القصاع',   addr:'دمشق - القصاع - شارع بغداد - بناء 21',   mar:'single',  occ:'مصمّمة' },
    { key:'kareem', nid:'04001000005', f:'كريم',   ab:'وليد',  l:'الديب',   m:'سعاد الأحمد', g:'male',   dob:'1979-05-30', ph:'0944100005', city:'دوما',  dist:'المركز',  addr:'ريف دمشق - دوما - الحي الشمالي',          mar:'married', occ:'تاجر', gov:'rif_dimashq' },
    { key:'suha',   nid:'04001000006', f:'سهى',    ab:'ماهر',  l:'العمر',   m:'نجاح القاضي', g:'female', dob:'1992-09-09', ph:'0944100006', city:'دمشق', dist:'الميدان',  addr:'دمشق - الميدان - شارع الميدان - بناء 3',  mar:'single',  occ:'ممرضة' },
    { key:'yousef', nid:'04002000001', f:'يوسف',   ab:'نبيل',  l:'القاضي',  m:'وفاء الحلبي', g:'male',   dob:'1978-02-14', ph:'0944200001', city:'دمشق', dist:'أبو رمانة',addr:'دمشق - أبو رمانة', occ:'طبيب قلبية' },
    { key:'heba',   nid:'04002000002', f:'هبة',    ab:'عماد',  l:'سلوم',    m:'ابتسام درويش',g:'female', dob:'1982-06-21', ph:'0944200002', city:'دمشق', dist:'المزة',    addr:'دمشق - المزة', occ:'طبيبة عظمية' },
    { key:'ziad',   nid:'04002000003', f:'زياد',   ab:'ناصر',  l:'الحلبي',  m:'منى الخوري',  g:'male',   dob:'1985-10-10', ph:'0944200003', city:'دمشق', dist:'المالكي',  addr:'دمشق - المالكي', occ:'طبيب عام' },
    { key:'maya',   nid:'04002000004', f:'مايا',   ab:'رامي',  l:'درويش',   m:'سلمى العلي',  g:'female', dob:'1987-04-04', ph:'0944200004', city:'دمشق', dist:'كفرسوسة', addr:'دمشق - كفرسوسة', occ:'طبيبة أطفال' },
    { key:'samer',  nid:'04003000001', f:'سامر',   ab:'جمال',  l:'الأحمد',  m:'رغداء سلوم',  g:'male',   dob:'1984-08-08', ph:'0944300001', city:'دمشق', dist:'المزة',    addr:'دمشق - المزة', occ:'طبيب أسنان' },
    { key:'nour',   nid:'04003000002', f:'نور',    ab:'حسن',   l:'الخوري',  m:'ريم القاضي',  g:'female', dob:'1989-12-12', ph:'0944300002', city:'دمشق', dist:'المالكي',  addr:'دمشق - المالكي', occ:'طبيبة أسنان' },
    { key:'firas',  nid:'04004000001', f:'فراس',   ab:'عدنان', l:'الشمالي', m:'هناء العمر',  g:'male',   dob:'1988-03-03', ph:'0944400001', city:'دمشق', dist:'الشعلان',  addr:'دمشق - الشعلان', occ:'صيدلاني' },
    { key:'dana',   nid:'04004000002', f:'دانا',   ab:'توفيق', l:'الحموي',  m:'سوسن الحسن',  g:'female', dob:'1991-11-11', ph:'0944400002', city:'دمشق', dist:'القصاع',   addr:'دمشق - القصاع', occ:'صيدلانية' },
    { key:'basel',  nid:'04005000001', f:'باسل',   ab:'رياض',  l:'العيسى',  m:'لينا الديب',  g:'male',   dob:'1990-05-05', ph:'0944500001', city:'دمشق', dist:'الميدان',  addr:'دمشق - الميدان', occ:'فني مخبر' },
    { key:'tala',   nid:'04005000002', f:'تالا',   ab:'سمير',  l:'الخطيب',  m:'دلال العلي',  g:'female', dob:'1993-07-07', ph:'0944500002', city:'دمشق', dist:'المزة',    addr:'دمشق - المزة', occ:'فنية مخبر' },
    { key:'admin',  nid:'04009000001', f:'عبدالله',ab:'مازن',  l:'الإداري', m:'سحر الشامي',  g:'male',   dob:'1980-01-01', ph:'0944900001', city:'دمشق', dist:'المزة',    addr:'دمشق - المزة', occ:'مدير النظام' },
  ];
  const P = {};
  for (const d of personDefs) {
    P[d.key] = await Person.create({
      nationalId:d.nid, firstName:d.f, fatherName:d.ab, lastName:d.l, motherName:d.m,
      dateOfBirth:new Date(d.dob), gender:d.g, maritalStatus:d.mar || 'single', occupation:d.occ,
      phoneNumber:d.ph, governorate:d.gov || 'damascus', city:d.city, district:d.dist, address:d.addr, isActive:true,
    });
  }
  console.log(`   • ${Object.keys(P).length} persons`);

  // ── (b) FACILITIES: hospitals, pharmacies, laboratories ────────────────────
  console.log('🏥 hospitals / pharmacies / laboratories...');
  const opHours = ['Sunday','Monday','Tuesday','Wednesday','Thursday'].map((day) => ({ day, openTime:'08:00', closeTime:'16:00', is24Hours:false }));

  const H = {};
  H.mouwasat = await Hospital.create({ name:'مشفى المواساة الجامعي', arabicName:'مشفى المواساة الجامعي', registrationNumber:'HOSP-DAM-001', hospitalLicense:'HL-DAM-001', hospitalType:'university', specializations:['قلبية','عظمية','أطفال','جراحة عامة'], phoneNumber:'0112120000', emergencyPhoneNumber:'0112120911', address:'دمشق - المزة - أوتوستراد المزة', governorate:'damascus', city:'دمشق', district:'المزة', numberOfBeds:600, numberOfOperatingRooms:12, hasEmergency:true, hasICU:true, hasLaboratory:true, hasPharmacy:true, hasRadiology:true, operatingHours:opHours, isActive:true, isAcceptingPatients:true });
  H.assad = await Hospital.create({ name:'مشفى الأسد الجامعي', arabicName:'مشفى الأسد الجامعي', registrationNumber:'HOSP-DAM-002', hospitalLicense:'HL-DAM-002', hospitalType:'university', specializations:['قلبية','أعصاب','جراحة'], phoneNumber:'0113140000', emergencyPhoneNumber:'0113140911', address:'دمشق - المزة - جادة المزة', governorate:'damascus', city:'دمشق', district:'المزة', numberOfBeds:550, numberOfOperatingRooms:10, hasEmergency:true, hasICU:true, hasLaboratory:true, hasPharmacy:true, hasRadiology:true, operatingHours:opHours, isActive:true, isAcceptingPatients:true });
  H.mujtahid = await Hospital.create({ name:'مشفى المجتهد', arabicName:'مشفى المجتهد', registrationNumber:'HOSP-DAM-003', hospitalLicense:'HL-DAM-003', hospitalType:'government', specializations:['طوارئ','باطنة'], phoneNumber:'0112221000', emergencyPhoneNumber:'0112221911', address:'دمشق - المجتهد', governorate:'damascus', city:'دمشق', district:'المجتهد', numberOfBeds:400, numberOfOperatingRooms:8, hasEmergency:true, hasICU:true, hasLaboratory:true, hasPharmacy:true, hasRadiology:true, operatingHours:opHours, isActive:true, isAcceptingPatients:true });

  const PH = {};
  PH.sham = await Pharmacy.create({ name:'صيدلية الشام', arabicName:'صيدلية الشام', registrationNumber:'PHR-DAM-001', pharmacyLicense:'PL-DAM-001', pharmacyType:'community', phoneNumber:'0113330001', address:'دمشق - الشعلان - شارع العابد', governorate:'damascus', city:'دمشق', district:'الشعلان', operatingHours:opHours, isActive:true, isAcceptingOrders:true });
  PH.noor = await Pharmacy.create({ name:'صيدلية النور', arabicName:'صيدلية النور', registrationNumber:'PHR-DAM-002', pharmacyLicense:'PL-DAM-002', pharmacyType:'community', phoneNumber:'0113330002', address:'دمشق - القصاع - شارع بغداد', governorate:'damascus', city:'دمشق', district:'القصاع', operatingHours:opHours, isActive:true, isAcceptingOrders:true });
  PH.markazia = await Pharmacy.create({ name:'صيدلية دمشق المركزية', arabicName:'صيدلية دمشق المركزية', registrationNumber:'PHR-DAM-003', pharmacyLicense:'PL-DAM-003', pharmacyType:'community', phoneNumber:'0113330003', address:'دمشق - الميدان - شارع الميدان', governorate:'damascus', city:'دمشق', district:'الميدان', operatingHours:opHours, isActive:true, isAcceptingOrders:true });

  const testCatalog = [
    { testCode:'CBC',   testName:'Complete Blood Count', arabicName:'تعداد دم كامل', category:'blood', price:15000, turnaroundTime:'يوم واحد', isAvailable:true },
    { testCode:'FBS',   testName:'Fasting Blood Sugar',  arabicName:'سكر صيامي',     category:'blood', price:8000,  turnaroundTime:'نفس اليوم', isAvailable:true },
    { testCode:'HbA1c', testName:'Glycated Hemoglobin',  arabicName:'خضاب سكري',     category:'blood', price:25000, turnaroundTime:'يوم واحد', isAvailable:true },
    { testCode:'LFT',   testName:'Liver Function Test',  arabicName:'وظائف كبد',     category:'blood', price:30000, turnaroundTime:'يوم واحد', isAvailable:true },
    { testCode:'URINE', testName:'Urine Analysis',       arabicName:'تحليل بول',     category:'urine', price:10000, turnaroundTime:'نفس اليوم', isAvailable:true },
  ];
  const L = {};
  L.damascus = await Laboratory.create({ name:'مخبر دمشق للتحاليل الطبية', arabicName:'مخبر دمشق للتحاليل الطبية', registrationNumber:'LAB-DAM-001', labLicense:'LL-DAM-001', labType:'independent', phoneNumber:'0114440001', address:'دمشق - المالكي - شارع الرشيد', governorate:'damascus', city:'دمشق', district:'المالكي', testCatalog, operatingHours:opHours, isActive:true, isAcceptingTests:true });
  L.sham = await Laboratory.create({ name:'مخبر الشام التشخيصي', arabicName:'مخبر الشام التشخيصي', registrationNumber:'LAB-DAM-002', labLicense:'LL-DAM-002', labType:'independent', phoneNumber:'0114440002', address:'دمشق - المزة - فيلات شرقية', governorate:'damascus', city:'دمشق', district:'المزة', testCatalog, operatingHours:opHours, isActive:true, isAcceptingTests:true });
  L.yarmouk = await Laboratory.create({ name:'مخبر اليرموك', arabicName:'مخبر اليرموك', registrationNumber:'LAB-DAM-003', labLicense:'LL-DAM-003', labType:'clinic_based', phoneNumber:'0114440003', address:'دمشق - الميدان', governorate:'damascus', city:'دمشق', district:'الميدان', testCatalog, operatingHours:opHours, isActive:true, isAcceptingTests:true });
  console.log('   • 3 hospitals, 3 pharmacies, 3 laboratories');

  // ── (c) MEDICATIONS (medicationCode auto-generated by hook) ────────────────
  console.log('💊 medications...');
  const medDefs = [
    { k:'paracetamol', t:'Panadol',    at:'بانادول',   s:'Paracetamol',                 as:'باراسيتامول',            cat:'analgesic',        form:'tablet',   str:'500mg',  rx:false },
    { k:'augmentin',   t:'Augmentin',  at:'أوغمنتين',  s:'Amoxicillin/Clavulanic Acid', as:'أموكسيسيلين/كلافولانيك', cat:'antibiotic',       form:'tablet',   str:'1g',     rx:true },
    { k:'amoxicillin', t:'Amoxil',     at:'أموكسيل',   s:'Amoxicillin',                 as:'أموكسيسيلين',            cat:'antibiotic',       form:'capsule',  str:'500mg',  rx:true },
    { k:'aspirin',     t:'Aspirin',    at:'أسبرين',    s:'Acetylsalicylic Acid',        as:'حمض أسيتيل ساليسيليك',   cat:'cardiovascular',   form:'tablet',   str:'100mg',  rx:false },
    { k:'ibuprofen',   t:'Brufen',     at:'بروفين',    s:'Ibuprofen',                   as:'إيبوبروفين',             cat:'analgesic',        form:'tablet',   str:'400mg',  rx:false },
    { k:'metformin',   t:'Glucophage', at:'غلوكوفاج',  s:'Metformin',                   as:'ميتفورمين',              cat:'antidiabetic',     form:'tablet',   str:'850mg',  rx:true },
    { k:'amlodipine',  t:'Norvasc',    at:'نورفاسك',   s:'Amlodipine',                  as:'أملوديبين',              cat:'antihypertensive', form:'tablet',   str:'5mg',    rx:true },
    { k:'atorvastatin',t:'Lipitor',    at:'ليبيتور',   s:'Atorvastatin',                as:'أتورفاستاتين',           cat:'cardiovascular',   form:'tablet',   str:'20mg',   rx:true },
    { k:'omeprazole',  t:'Omepak',     at:'أوميباك',   s:'Omeprazole',                  as:'أوميبرازول',             cat:'gastrointestinal', form:'capsule',  str:'20mg',   rx:true },
    { k:'cetirizine',  t:'Zyrtec',     at:'زيرتك',     s:'Cetirizine',                  as:'سيتيريزين',              cat:'antihistamine',    form:'tablet',   str:'10mg',   rx:false },
    { k:'salbutamol',  t:'Ventolin',   at:'فينتولين',  s:'Salbutamol',                  as:'سالبوتامول',             cat:'respiratory',      form:'inhaler',  str:'100mcg', rx:true },
    { k:'insulin',     t:'Lantus',     at:'لانتوس',    s:'Insulin Glargine',            as:'أنسولين غلارجين',        cat:'hormonal',         form:'injection',str:'100IU/ml',rx:true },
  ];
  const MED = {};
  let medSeq = 0;
  for (const d of medDefs) {
    medSeq += 1;
    MED[d.k] = await Medication.create({
      medicationCode: `MED-${String(medSeq).padStart(5, '0')}`,
      tradeName:d.t, arabicTradeName:d.at, scientificName:d.s, arabicScientificName:d.as,
      manufacturer:'الشركة السورية للصناعات الدوائية', countryOfOrigin:'سوريا',
      strength:d.str, dosageForm:d.form, category:d.cat,
      requiresPrescription:d.rx, controlledSubstance:false, isAvailable:true, isDiscontinued:false,
      storageConditions:'يُحفظ بدرجة حرارة أقل من 25°م',
    });
  }
  console.log(`   • ${Object.keys(MED).length} medications`);

  // ── (d) STAFF: doctors, dentists, pharmacists, lab techs, admin ────────────
  console.log('🩺 staff...');
  const D = {};
  D.yousef = await Doctor.create({ personId:P.yousef._id, medicalLicenseNumber:'MD-DAM-1001', specialization:'cardiology', subSpecialization:'كهربائية القلب', yearsOfExperience:18, medicalDegree:'بورد سوري - أمراض قلبية', hospitalId:H.mouwasat._id, hospitalAffiliation:'مشفى المواساة الجامعي', position:'consultant', employmentType:'full-time', availableDays:['Sunday','Tuesday','Thursday'], consultationFee:75000, followUpFee:40000, currency:'SYP', isECGSpecialist:true, isAvailable:true, isAcceptingNewPatients:true, verificationStatus:'verified' });
  D.heba = await Doctor.create({ personId:P.heba._id, medicalLicenseNumber:'MD-DAM-1002', specialization:'orthopedics', yearsOfExperience:14, medicalDegree:'بورد سوري - جراحة عظمية', hospitalId:H.assad._id, hospitalAffiliation:'مشفى الأسد الجامعي', position:'specialist', employmentType:'full-time', availableDays:['Monday','Wednesday'], consultationFee:70000, followUpFee:35000, currency:'SYP', isECGSpecialist:false, isAvailable:true, isAcceptingNewPatients:true, verificationStatus:'verified' });
  D.ziad = await Doctor.create({ personId:P.ziad._id, medicalLicenseNumber:'MD-DAM-1003', specialization:'general_practice', yearsOfExperience:9, medicalDegree:'دكتور في الطب العام', hospitalId:H.mujtahid._id, hospitalAffiliation:'مشفى المجتهد', position:'specialist', employmentType:'full-time', availableDays:['Sunday','Monday','Wednesday','Thursday'], consultationFee:50000, followUpFee:25000, currency:'SYP', isECGSpecialist:false, isAvailable:true, isAcceptingNewPatients:true, verificationStatus:'verified' });
  D.maya = await Doctor.create({ personId:P.maya._id, medicalLicenseNumber:'MD-DAM-1004', specialization:'pediatrics', yearsOfExperience:11, medicalDegree:'بورد سوري - أطفال', hospitalId:H.mouwasat._id, hospitalAffiliation:'مشفى المواساة الجامعي', position:'specialist', employmentType:'part-time', availableDays:['Tuesday','Thursday'], consultationFee:60000, followUpFee:30000, currency:'SYP', isECGSpecialist:false, isAvailable:true, isAcceptingNewPatients:true, verificationStatus:'verified' });

  const DENT = {};
  DENT.samer = await Dentist.create({ personId:P.samer._id, dentalLicenseNumber:'DEN-DAM-2001', specialization:'General Dentistry', yearsOfExperience:12, consultationFee:45000, currency:'SYP', hospitalId:H.mouwasat._id, position:'specialist', employmentType:'full-time', availableDays:['Sunday','Tuesday','Thursday'], isAvailable:true, isAcceptingNewPatients:true, verificationStatus:'verified' });
  DENT.nour = await Dentist.create({ personId:P.nour._id, dentalLicenseNumber:'DEN-DAM-2002', specialization:'Orthodontics', yearsOfExperience:8, consultationFee:55000, currency:'SYP', position:'specialist', employmentType:'part-time', availableDays:['Monday','Wednesday'], isAvailable:true, isAcceptingNewPatients:true, verificationStatus:'verified' });

  const PHARM = {};
  PHARM.firas = await Pharmacist.create({ personId:P.firas._id, pharmacyLicenseNumber:'PHM-DAM-3001', pharmacyId:PH.sham._id, degree:'PharmD', specialization:'Community Pharmacy', yearsOfExperience:7, employmentType:'full-time', isAvailable:true, totalPrescriptionsDispensed:0 });
  PHARM.dana = await Pharmacist.create({ personId:P.dana._id, pharmacyLicenseNumber:'PHM-DAM-3002', pharmacyId:PH.noor._id, degree:'BSc Pharmacy', specialization:'Clinical Pharmacy', yearsOfExperience:5, employmentType:'full-time', isAvailable:true, totalPrescriptionsDispensed:0 });

  const LT = {};
  LT.basel = await LabTechnician.create({ personId:P.basel._id, licenseNumber:'LTC-DAM-4001', laboratoryId:L.damascus._id, degree:'BSc Medical Laboratory', specialization:'Clinical Chemistry', position:'senior_technician', yearsOfExperience:8, isAvailable:true, totalTestsPerformed:0 });
  LT.tala = await LabTechnician.create({ personId:P.tala._id, licenseNumber:'LTC-DAM-4002', laboratoryId:L.sham._id, degree:'Diploma', specialization:'Hematology', position:'technician', yearsOfExperience:4, isAvailable:true, totalTestsPerformed:0 });

  await Admin.create({ personId:P.admin._id, adminLevel:'super_admin', permissions:['manage_doctors','manage_facilities','view_logs','manage_accounts','approve_requests'], department:'إدارة النظام' });
  console.log('   • 4 doctors, 2 dentists, 2 pharmacists, 2 lab techs, 1 admin');

  // ── (e) (children removed by request — no children created) ──────────────
  const todayYmd = ymd();

  // ── (f) ACCOUNTS (login for everyone) ──────────────────────────────────────
  console.log('🔐 accounts...');
  await createAccount({ email:'admin@patient360.gov.sy',          password:'Admin@2026',  roles:['admin'],          personId:P.admin._id,  name:'عبدالله الإداري',        roleLabel:'admin' });
  await createAccount({ email:'yousef.alqadi@patient360.gov.sy',  password:'Yousef@2026', roles:['doctor'],         personId:P.yousef._id, name:'د. يوسف القاضي (قلبية)',  roleLabel:'doctor' });
  await createAccount({ email:'heba.salloum@patient360.gov.sy',   password:'Heba@2026',   roles:['doctor'],         personId:P.heba._id,   name:'د. هبة سلوم (عظمية)',     roleLabel:'doctor' });
  await createAccount({ email:'ziad.alhalabi@patient360.gov.sy',  password:'Ziad@2026',   roles:['doctor'],         personId:P.ziad._id,   name:'د. زياد الحلبي (عام)',    roleLabel:'doctor' });
  await createAccount({ email:'maya.darwish@patient360.gov.sy',   password:'Maya@2026',   roles:['doctor'],         personId:P.maya._id,   name:'د. مايا درويش (أطفال)',   roleLabel:'doctor' });
  await createAccount({ email:'samer.alahmad@patient360.gov.sy',  password:'Samer@2026',  roles:['dentist'],        personId:P.samer._id,  name:'د. سامر الأحمد (أسنان)',  roleLabel:'dentist' });
  await createAccount({ email:'nour.alkhoury@patient360.gov.sy',  password:'Nour@2026',   roles:['dentist'],        personId:P.nour._id,   name:'د. نور الخوري (تقويم)',   roleLabel:'dentist' });
  await createAccount({ email:'firas.adnan@patient360.gov.sy',    password:'Firas@2026',  roles:['pharmacist'],     personId:P.firas._id,  name:'الصيدلاني فراس الشمالي',   roleLabel:'pharmacist' });
  await createAccount({ email:'dana.tawfiq@patient360.gov.sy',    password:'Dana@2026',   roles:['pharmacist'],     personId:P.dana._id,   name:'الصيدلانية دانا الحموي',   roleLabel:'pharmacist' });
  await createAccount({ email:'basel.riad@patient360.gov.sy',     password:'Basel@2026',  roles:['lab_technician'], personId:P.basel._id,  name:'فني المخبر باسل العيسى',   roleLabel:'lab_technician' });
  await createAccount({ email:'tala.samir@patient360.gov.sy',     password:'Tala@2026',   roles:['lab_technician'], personId:P.tala._id,   name:'فنية المخبر تالا الخطيب',  roleLabel:'lab_technician' });
  await createAccount({ email:'ahmad.alali@patient360.gov.sy',    password:'Ahmad@2026',  roles:['patient'],        personId:P.ahmad._id,  name:'أحمد العلي',  roleLabel:'patient' });
  await createAccount({ email:'layla.alhasan@patient360.gov.sy',  password:'Layla@2026',  roles:['patient'],        personId:P.layla._id,  name:'ليلى الحسن',  roleLabel:'patient' });
  await createAccount({ email:'omar.alkhatib@patient360.gov.sy',  password:'Omar@2026',   roles:['patient'],        personId:P.omar._id,   name:'عمر الخطيب',  roleLabel:'patient' });
  await createAccount({ email:'rana.alshami@patient360.gov.sy',   password:'Rana@2026',   roles:['patient'],        personId:P.rana._id,   name:'رنا الشامي',  roleLabel:'patient' });
  await createAccount({ email:'kareem.aldeeb@patient360.gov.sy',  password:'Kareem@2026', roles:['patient'],        personId:P.kareem._id, name:'كريم الديب',  roleLabel:'patient' });
  await createAccount({ email:'suha.alomar@patient360.gov.sy',    password:'Suha@2026',   roles:['patient'],        personId:P.suha._id,   name:'سهى العمر',   roleLabel:'patient' });
  console.log(`   • ${credentials.length} accounts`);

  // ── (g) PATIENT PROFILES (6 adults + 2 children = 8) ───────────────────────
  console.log('🩻 patient profiles...');
  await Patient.create({ personId:P.ahmad._id,  bloodType:'O+',  rhFactor:'positive', height:178, weight:88, smokingStatus:'former_smoker', alcoholConsumption:'none', exerciseFrequency:'light', dietType:'regular', chronicDiseases:['ارتفاع ضغط الدم','ارتفاع الكوليسترول'], allergies:['البنسلين'], familyHistory:['أمراض قلبية (الأب)'], currentMedications:['أملوديبين','أتورفاستاتين'], emergencyContact:{ name:'ليلى الحسن', relationship:'الزوجة', phoneNumber:'0944100002' } });
  await Patient.create({ personId:P.layla._id,  bloodType:'A+',  rhFactor:'positive', height:165, weight:62, smokingStatus:'non-smoker', alcoholConsumption:'none', exerciseFrequency:'moderate', dietType:'regular', chronicDiseases:[], allergies:['حبوب اللقاح'], familyHistory:['سكري (الأم)'], emergencyContact:{ name:'أحمد العلي', relationship:'الزوج', phoneNumber:'0944100001' } });
  await Patient.create({ personId:P.omar._id,   bloodType:'B+',  rhFactor:'positive', height:172, weight:80, smokingStatus:'current_smoker', alcoholConsumption:'occasional', exerciseFrequency:'sedentary', dietType:'regular', chronicDiseases:['السكري النوع الثاني'], allergies:[], familyHistory:[], currentMedications:['ميتفورمين'], emergencyContact:{ name:'هدى الشامي', relationship:'الأم', phoneNumber:'0944100099' } });
  await Patient.create({ personId:P.rana._id,   bloodType:'AB+', rhFactor:'positive', height:160, weight:55, smokingStatus:'non-smoker', alcoholConsumption:'none', exerciseFrequency:'active', dietType:'vegetarian', chronicDiseases:[], allergies:['المكسرات'], familyHistory:[], emergencyContact:{ name:'فادي الشامي', relationship:'الأب', phoneNumber:'0944100098' } });
  await Patient.create({ personId:P.kareem._id, bloodType:'O-',  rhFactor:'negative', height:175, weight:95, smokingStatus:'current_smoker', alcoholConsumption:'none', exerciseFrequency:'sedentary', dietType:'regular', chronicDiseases:['ارتفاع ضغط الدم'], allergies:[], familyHistory:['أمراض قلبية (الأب)'], emergencyContact:{ name:'سعاد الأحمد', relationship:'الزوجة', phoneNumber:'0944100097' } });
  await Patient.create({ personId:P.suha._id,   bloodType:'A-',  rhFactor:'negative', height:168, weight:58, smokingStatus:'non-smoker', alcoholConsumption:'none', exerciseFrequency:'moderate', dietType:'halal', chronicDiseases:[], allergies:[], familyHistory:[], emergencyContact:{ name:'ماهر العمر', relationship:'الأب', phoneNumber:'0944100096' } });
  console.log('   • 6 patient profiles');

  // ── (h) PHARMACY INVENTORY ─────────────────────────────────────────────────
  console.log('📦 pharmacy inventory...');
  for (const med of [MED.paracetamol, MED.amoxicillin, MED.ibuprofen, MED.metformin, MED.amlodipine, MED.cetirizine]) {
    await PharmacyInventory.create({ pharmacyId:PH.sham._id, medicationId:med._id, currentStock:200, minimumStock:30, maximumStock:500, lowStockAlert:false, expiryAlert:false, unitPrice:5000, currency:'SYP', batches:[{ batchNumber:'B-2026-001', quantity:200, expiryDate:daysAhead(540), receivedDate:daysAgo(20), supplier:'الموزّع الوطني', unitCost:3500 }], lastRestockedAt:daysAgo(20) });
  }
  console.log('   • 6 inventory rows for صيدلية الشام');

  // ── (i) AVAILABILITY SLOTS ─────────────────────────────────────────────────
  console.log('🗓️  availability slots...');
  for (let i = 1; i <= 4; i++) await AvailabilitySlot.create({ doctorId:D.yousef._id, hospitalId:H.mouwasat._id, date:daysAhead(i), startTime:'10:00', endTime:'10:30', slotDuration:30, isAvailable:true, maxBookings:1, currentBookings:0, status:'available' });
  for (let i = 1; i <= 3; i++) await AvailabilitySlot.create({ dentistId:DENT.samer._id, hospitalId:H.mouwasat._id, date:daysAhead(i), startTime:'12:00', endTime:'12:30', slotDuration:30, isAvailable:true, maxBookings:1, currentBookings:0, status:'available' });
  await AvailabilitySlot.create({ doctorId:D.heba._id, hospitalId:H.assad._id, date:daysAhead(2), startTime:'11:00', endTime:'11:30', slotDuration:30, isAvailable:false, maxBookings:1, currentBookings:1, status:'booked' });
  console.log('   • 8 slots');

  // ── (j) ENCOUNTERS: appointments → visits → prescriptions → lab tests ──────
  console.log('📅 appointments + 🩺 visits + 📝 prescriptions + 🧪 lab tests + 💊 dispensing...');

  // Encounter #1 — Ahmad ↔ Dr. Yousef (cardiology), completed
  const apptAhmad = await Appointment.create({ appointmentType:'doctor', patientPersonId:P.ahmad._id, doctorId:D.yousef._id, hospitalId:H.mouwasat._id, appointmentDate:daysAgo(7), appointmentTime:'10:00', estimatedDuration:30, reasonForVisit:'متابعة ضغط الدم وألم خفيف بالصدر', status:'completed', bookingMethod:'mobile_app', priority:'routine', paymentStatus:'paid', paymentMethod:'cash' });
  const visitAhmad = await Visit.create({ visitType:'regular', patientPersonId:P.ahmad._id, doctorId:D.yousef._id, hospitalId:H.mouwasat._id, appointmentId:apptAhmad._id, visitDate:daysAgo(7), status:'completed', chiefComplaint:'ألم خفيف بالصدر مع تعب عند الجهد', diagnosis:'ارتفاع ضغط دم غير مضبوط - يُنصح بتعديل الجرعة', vitalSigns:{ bloodPressureSystolic:150, bloodPressureDiastolic:95, heartRate:82, oxygenSaturation:98, temperature:36.8, weight:88, height:178 }, prescribedMedications:[ { medicationName:'أملوديبين', dosage:'5mg', frequency:'مرة يومياً', duration:'30 يوم', route:'oral', instructions:'يؤخذ صباحاً', quantity:30 }, { medicationName:'أتورفاستاتين', dosage:'20mg', frequency:'مرة مساءً', duration:'30 يوم', route:'oral', instructions:'يؤخذ بعد العشاء', quantity:30 } ], doctorNotes:'مراجعة بعد شهر مع تخطيط قلب', followUpDate:daysAhead(23), followUpNotes:'تكرار قياس الضغط', paymentStatus:'paid', paymentMethod:'cash' });
  await Appointment.findByIdAndUpdate(apptAhmad._id, { visitId:visitAhmad._id });
  const rxAhmad = await Prescription.create({ prescriptionNumber:`RX-${todayYmd}-00001`, patientPersonId:P.ahmad._id, doctorId:D.yousef._id, visitId:visitAhmad._id, prescriptionDate:daysAgo(7), expiryDate:daysAhead(23), medications:[ { medicationId:MED.amlodipine._id, medicationName:'أملوديبين', arabicName:'أملوديبين', dosage:'5mg', frequency:'مرة يومياً', duration:'30 يوم', route:'oral', instructions:'صباحاً', quantity:30, isDispensed:false }, { medicationId:MED.atorvastatin._id, medicationName:'أتورفاستاتين', arabicName:'أتورفاستاتين', dosage:'20mg', frequency:'مرة مساءً', duration:'30 يوم', route:'oral', instructions:'بعد العشاء', quantity:30, isDispensed:false } ], status:'active', printCount:1, prescriptionNotes:'يمنع التوقف عن الدواء دون استشارة' });
  const labAhmad = await LabTest.create({ testNumber:`LAB-${todayYmd}-00001`, patientPersonId:P.ahmad._id, orderedBy:D.yousef._id, orderedByModel:'Doctor', visitId:visitAhmad._id, laboratoryId:L.damascus._id, orderDate:daysAgo(7), scheduledDate:daysAgo(6), testsOrdered:[ { testCode:'CBC', testName:'تعداد دم كامل', notes:'' }, { testCode:'FBS', testName:'سكر صيامي', notes:'صائم 8 ساعات' }, { testCode:'HbA1c', testName:'خضاب سكري', notes:'' } ], testCategory:'blood', priority:'routine', sampleType:'blood', status:'completed', sampleCollectedAt:daysAgo(6), completedAt:daysAgo(5), testResults:[ { testCode:'FBS', testName:'سكر صيامي', value:'112', numericValue:112, unit:'mg/dL', referenceRange:'70-100', isAbnormal:true, isCritical:false }, { testCode:'HbA1c', testName:'خضاب سكري', value:'6.1', numericValue:6.1, unit:'%', referenceRange:'< 5.7', isAbnormal:true, isCritical:false } ], isCritical:false, isViewedByDoctor:true, isViewedByPatient:false, totalCost:48000, currency:'SYP' });

  // Encounter #2 — Omar ↔ Dr. Samer (dental), completed
  const apptOmar = await Appointment.create({ appointmentType:'dentist', patientPersonId:P.omar._id, dentistId:DENT.samer._id, hospitalId:H.mouwasat._id, appointmentDate:daysAgo(10), appointmentTime:'12:00', estimatedDuration:30, reasonForVisit:'ألم في الضرس السفلي', status:'completed', bookingMethod:'online', priority:'routine', paymentStatus:'paid', paymentMethod:'cash' });
  const visitOmar = await Visit.create({ visitType:'dental', patientPersonId:P.omar._id, dentistId:DENT.samer._id, hospitalId:H.mouwasat._id, appointmentId:apptOmar._id, visitDate:daysAgo(10), status:'completed', chiefComplaint:'ألم وتسوّس في الضرس السفلي الأيمن', diagnosis:'تسوّس عميق - يحتاج حشوة', doctorNotes:'تم وضع حشوة مؤقتة، مراجعة بعد أسبوع', followUpDate:daysAgo(3), paymentStatus:'paid', paymentMethod:'cash' });
  await Appointment.findByIdAndUpdate(apptOmar._id, { visitId:visitOmar._id });

  // Encounter #3 — Kareem ↔ Dr. Ziad (general) → dispensed Rx
  const visitKareem = await Visit.create({ visitType:'regular', patientPersonId:P.kareem._id, doctorId:D.ziad._id, hospitalId:H.mujtahid._id, visitDate:daysAgo(5), status:'completed', chiefComplaint:'حرارة وألم بالحلق منذ يومين', diagnosis:'التهاب لوزتين جرثومي', vitalSigns:{ bloodPressureSystolic:128, bloodPressureDiastolic:82, heartRate:90, oxygenSaturation:97, temperature:38.5 }, prescribedMedications:[ { medicationName:'أموكسيسيلين', dosage:'500mg', frequency:'3 مرات يومياً', duration:'7 أيام', route:'oral', instructions:'بعد الأكل', quantity:21 } ], doctorNotes:'راحة وسوائل', paymentStatus:'paid', paymentMethod:'cash' });
  const rxKareem = await Prescription.create({ prescriptionNumber:`RX-${todayYmd}-00002`, patientPersonId:P.kareem._id, doctorId:D.ziad._id, visitId:visitKareem._id, prescriptionDate:daysAgo(5), expiryDate:daysAhead(25), medications:[ { medicationId:MED.amoxicillin._id, medicationName:'أموكسيسيلين', arabicName:'أموكسيسيلين', dosage:'500mg', frequency:'3 مرات يومياً', duration:'7 أيام', route:'oral', instructions:'بعد الأكل', quantity:21, isDispensed:true, dispensedAt:daysAgo(5) } ], status:'dispensed', printCount:1 });
  const dispKareem = await PharmacyDispensing.create({ dispensingNumber:`DISP-${todayYmd}-00001`, pharmacyId:PH.sham._id, pharmacistId:PHARM.firas._id, patientPersonId:P.kareem._id, dispensingType:'prescription_based', prescriptionId:rxKareem._id, prescriptionNumber:rxKareem.prescriptionNumber, medicationsDispensed:[ { medicationId:MED.amoxicillin._id, medicationName:'أموكسيسيلين', quantityDispensed:21, batchNumber:'B-2026-001', expiryDate:daysAhead(540), unitPrice:5000, isGenericSubstitute:false, pharmacistNotes:'تم الصرف كاملاً' } ], dispensingDate:daysAgo(5), totalCost:105000, currency:'SYP', paymentMethod:'cash' });
  await Prescription.findByIdAndUpdate(rxKareem._id, { dispensingId:dispKareem._id });

  // A couple of upcoming/cancelled appointments for variety
  const apptLayla = await Appointment.create({ appointmentType:'doctor', patientPersonId:P.layla._id, doctorId:D.heba._id, hospitalId:H.assad._id, appointmentDate:daysAhead(2), appointmentTime:'11:00', estimatedDuration:30, reasonForVisit:'ألم في الركبة', status:'scheduled', bookingMethod:'mobile_app', priority:'routine', paymentStatus:'pending', paymentMethod:'cash' });
  await Appointment.create({ appointmentType:'dentist', patientPersonId:P.rana._id, dentistId:DENT.nour._id, appointmentDate:daysAgo(2), appointmentTime:'12:00', estimatedDuration:30, reasonForVisit:'استشارة تقويم', status:'cancelled', cancellationReason:'patient_request', cancelledAt:daysAgo(3), bookingMethod:'online', priority:'routine', paymentStatus:'cancelled' });

  // ── (k) REVIEWS ────────────────────────────────────────────────────────────
  console.log('⭐ reviews...');
  await Review.create({ reviewerPersonId:P.ahmad._id, doctorId:D.yousef._id, visitId:visitAhmad._id, rating:5, reviewText:'طبيب ممتاز وشرح مفصّل للحالة، أنصح فيه.', status:'approved', isAnonymous:false });
  await Review.create({ reviewerPersonId:P.omar._id, dentistId:DENT.samer._id, visitId:visitOmar._id, rating:4, reviewText:'تعامل لطيف والعلاج كان مريح.', status:'approved', isAnonymous:false });
  console.log('   • 2 reviews');

  // ── (l) NOTIFICATIONS ──────────────────────────────────────────────────────
  console.log('🔔 notifications...');
  const accAhmad = await Account.findOne({ email:'ahmad.alali@patient360.gov.sy' });
  const accLayla = await Account.findOne({ email:'layla.alhasan@patient360.gov.sy' });
  await Notification.create({ recipientId:accAhmad._id, recipientType:'patient', type:'appointment_confirmed', title:'تأكيد الموعد', message:'تم تأكيد موعدك مع د. يوسف القاضي.', status:'delivered', priority:'medium', channels:['push','in_app'], relatedId:apptAhmad._id, relatedType:'appointments', sentAt:daysAgo(7), deliveredAt:daysAgo(7) });
  await Notification.create({ recipientId:accAhmad._id, recipientType:'patient', type:'lab_results_ready', title:'نتائج المختبر جاهزة', message:'نتائج تحاليلك في مخبر دمشق أصبحت جاهزة.', status:'sent', priority:'high', channels:['push','in_app'], relatedId:labAhmad._id, relatedType:'lab_tests', sentAt:daysAgo(5) });
  await Notification.create({ recipientId:accLayla._id, recipientType:'patient', type:'appointment_reminder', title:'تذكير بموعد', message:'لديك موعد غداً مع د. هبة سلوم الساعة 11:00.', status:'pending', priority:'medium', channels:['push','in_app'], relatedId:apptLayla._id, relatedType:'appointments', expiresAt:daysAhead(2) });
  console.log('   • 3 notifications');

  // ── (m) EMERGENCY REPORTS (aiConfidence MUST be double → fractional) ───────
  console.log('🚑 emergency reports...');
  try {
    await EmergencyReport.create({ patientPersonId:P.suha._id, reportedAt:daysAgo(4), inputType:'text', textDescription:'حروق سطحية بسيطة على اليد من الماء الساخن، احمرار خفيف.', aiRiskLevel:'moderate', aiFirstAid:['تبريد الحرق بماء فاتر 10-15 دقيقة','تغطية المنطقة بشاش معقّم','عدم فقع الفقاعات','مراجعة الطبيب إذا ازداد الألم'], aiConfidence:0.82, aiModelVersion:'redwan-fastapi-v1.0.0', aiProcessedAt:daysAgo(4), location:{ type:'Point', coordinates:[36.2919, 33.5102] }, locationAddress:'دمشق - الميدان', ambulanceCalled:false, ambulanceStatus:'not_called', status:'resolved', resolvedAt:daysAgo(4), resolutionNote:'حالة بسيطة - إسعاف منزلي' });
    await EmergencyReport.create({ patientPersonId:P.omar._id, reportedAt:daysAgo(1), inputType:'combined', textDescription:'ألم شديد بالصدر وضيق نفس.', aiRiskLevel:'high', aiFirstAid:['اجلس بوضعية مريحة وحاول التنفس بهدوء','اتصل بالإسعاف فوراً','إذا وُصف لك دواء قلبي خذه حسب التعليمات'], aiConfidence:0.91, aiModelVersion:'redwan-fastapi-v1.0.0', aiProcessedAt:daysAgo(1), location:{ type:'Point', coordinates:[36.3012, 33.5167] }, locationAddress:'دمشق - كفرسوسة', ambulanceCalled:true, ambulanceCalledAt:daysAgo(1), ambulanceStatus:'dispatched', status:'active' });
    console.log('   • 2 emergency reports');
  } catch (e) {
    console.warn('   ⚠ emergency_reports skipped (شكل aiFirstAid مختلف بالموديل):', e.message);
  }

  // ── (n) OPTIONAL: one pending doctor_request + one pending facility_request ─
  console.log('📨 pending requests (optional)...');
  if (DoctorRequest) {
    try {
      await DoctorRequest.create({ requestId:`DREQ-${todayYmd}-00001`, requestType:'doctor', firstName:'وسيم', fatherName:'سامر', lastName:'العطار', motherName:'هالة النجار', nationalId:'04002000099', dateOfBirth:new Date('1986-06-06'), gender:'male', email:'wassim.alattar@gmail.com', phoneNumber:'0944200099', specialization:'dermatology', medicalLicenseNumber:'MD-DAM-9999', yearsOfExperience:10, consultationFee:60000, currency:'SYP', governorate:'damascus', city:'دمشق', address:'دمشق - المزة', hospitalAffiliation:'عيادة خاصة', availableDays:['Monday','Wednesday'], status:'pending' });
      console.log('   • 1 pending doctor request');
    } catch (e) { console.warn('   ⚠ doctor_request skipped:', e.message); }
  }
  if (FacilityRequest) {
    try {
      await FacilityRequest.create({ requestNumber:`FREQ-${todayYmd}-00001`, facilityType:'pharmacy', name:'صيدلية الحياة', arabicName:'صيدلية الحياة', license:'PL-DAM-NEW-01', phoneNumber:'0113330099', email:'alhayat.pharma@gmail.com', governorate:'damascus', city:'دمشق', district:'المزة', address:'دمشق - المزة - شارع الجلاء', submittedByEmail:'owner.alhayat@gmail.com', submittedByName:'مالك الصيدلية', submittedByPhone:'0944000099', status:'pending', notes:'طلب إضافة صيدلية جديدة' });
      console.log('   • 1 pending facility request');
    } catch (e) { console.warn('   ⚠ facility_request skipped:', e.message); }
  }
}

// ════════════════════════════════════════════════════════════════════════════
//  3) CREDENTIALS OUTPUT
// ════════════════════════════════════════════════════════════════════════════
function writeCredentials() {
  const outDir = __dirname;
  fs.writeFileSync(path.join(outDir, 'credentials.json'), JSON.stringify(credentials, null, 2), 'utf8');
  const lines = [];
  lines.push('Patient 360° — حسابات البيانات التجريبية (Demo Accounts)');
  lines.push('='.repeat(70));
  lines.push(`${'#'.padEnd(3)} ${'الدور / Role'.padEnd(18)} ${'الإيميل / Email'.padEnd(38)} كلمة المرور`);
  lines.push('-'.repeat(70));
  credentials.forEach((c, i) => {
    lines.push(`${String(i + 1).padEnd(3)} ${c.role.padEnd(18)} ${c.email.padEnd(38)} ${c.password}`);
  });
  lines.push('-'.repeat(70));
  lines.push(`الإجمالي: ${credentials.length} حساب`);
  fs.writeFileSync(path.join(outDir, 'credentials.txt'), lines.join('\n'), 'utf8');

  console.log('\n' + lines.join('\n'));
  console.log('\n📄 تم حفظ: credentials.json + credentials.txt بجانب السكربت.');
}

// ════════════════════════════════════════════════════════════════════════════
//  MAIN
// ════════════════════════════════════════════════════════════════════════════
(async function main() {
  console.log('🔌 Connecting to', MONGO_URI);
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected.');
    await wipe();
    await seed();
    writeCredentials();
    console.log('\n🎉 Seeding complete.');
    await mongoose.disconnect();
    process.exit(0);
  } catch (err) {
    console.error('\n❌ Seeding failed:', err);
    try { await mongoose.disconnect(); } catch (_) {}
    process.exit(1);
  }
})();
