// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50U1udbSS_2Hks_oMd7EexZhjbFtjqEQ',
    appId: '1:446133790040:web:7b513c2fffe3e7be51712d',
    messagingSenderId: '446133790040',
    projectId: 'patient360-bea25',
    authDomain: 'patient360-bea25.firebaseapp.com',
    storageBucket: 'patient360-bea25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHL3U5gD4EhpSHZ4Quyj5nqPCGtwRfF8',
    appId: '1:446133790040:android:ee6d2d995573f76951712d',
    messagingSenderId: '446133790040',
    projectId: 'patient360-bea25',
    storageBucket: 'patient360-bea25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHCShy4WtoyeDdkrhsiDY0fhlWP7J00PM',
    appId: '1:446133790040:ios:21d777a092b9669551712d',
    messagingSenderId: '446133790040',
    projectId: 'patient360-bea25',
    storageBucket: 'patient360-bea25.firebasestorage.app',
    iosBundleId: 'sy.gov.patient360.mobile.patient360Mobile',
  );
}
