/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  FacilityRequest Model — Patient 360°
 *  ─────────────────────────────────────────────────────────────────────────
 *  📁 Path: backend/models/FacilityRequest.js
 *  🆕 NEW in v2.2 (2026-05-27)
 *
 *  Stores requests from pharmacists/lab technicians to register a new
 *  pharmacy or laboratory that is not yet in the system.
 *
 *  Workflow:
 *    1. SignUp.jsx — user searches for their facility.
 *    2. If not found, they submit a FacilityRequest along with their
 *       DoctorRequest (with requestType='pharmacist' or 'lab_technician').
 *    3. Admin opens "Facility Requests" tab and reviews.
 *    4. On approval → backend creates the actual pharmacy/laboratory and
 *       updates linkedDoctorRequest.pharmacyId / laboratoryId.
 *    5. On rejection → the linked doctor_request also gets rejected with
 *       the same reason.
 * ═══════════════════════════════════════════════════════════════════════════
 */

const mongoose = require('mongoose');
const { Schema } = mongoose;

// ── Enums ───────────────────────────────────────────────────────────────────
const FACILITY_TYPES = ['pharmacy', 'laboratory'];

const PHARMACY_SUB_TYPES = ['community', 'hospital', 'clinic', 'online'];

const LAB_SUB_TYPES = ['independent', 'hospital_based', 'clinic_based', 'specialized'];

const GOVERNORATES = [
  'damascus', 'aleppo', 'homs', 'hama', 'latakia', 'tartus',
  'idlib', 'deir_ez_zor', 'raqqa', 'hasakah', 'daraa',
  'as_suwayda', 'quneitra', 'rif_dimashq',
];

const REQUEST_STATUSES = ['pending', 'approved', 'rejected'];

const REJECTION_REASONS = [
  'duplicate', 'invalid_info', 'unverifiable', 'incomplete', 'other',
];

// ── Schema ──────────────────────────────────────────────────────────────────
const FacilityRequestSchema = new Schema(
  {
    // Identifier — generated by controller as FREQ-YYYYMMDD-XXXXX
    requestNumber: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      uppercase: true,
    },

    facilityType: {
      type: String,
      required: true,
      enum: FACILITY_TYPES,
      index: true,
    },

    // ── Facility basic info ───────────────────────────────────────────────
    name: {
      type: String,
      required: [true, 'اسم المنشأة مطلوب'],
      trim: true,
      minlength: 2,
      maxlength: 200,
    },
    arabicName: {
      type: String,
      trim: true,
      maxlength: 200,
    },
    license: {
      type: String,
      trim: true,
      maxlength: 100,
    },

    // Sub-type within facilityType
    specificType: {
      type: String,
      trim: true,
      validate: {
        validator: function (v) {
          if (!v) return true; // optional
          if (this.facilityType === 'pharmacy') return PHARMACY_SUB_TYPES.includes(v);
          if (this.facilityType === 'laboratory') return LAB_SUB_TYPES.includes(v);
          return true;
        },
        message: 'النوع الفرعي غير صالح لهذا النوع من المنشآت',
      },
    },

    // ── Contact ────────────────────────────────────────────────────────────
    phoneNumber: { type: String, trim: true },
    email: { type: String, trim: true, lowercase: true },

    // ── Location ───────────────────────────────────────────────────────────
    governorate: {
      type: String,
      required: true,
      enum: GOVERNORATES,
    },
    city: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
    },
    district: { type: String, trim: true },
    address: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
    },

    // ── Submitter info ─────────────────────────────────────────────────────
    submittedByEmail: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
      match: [/^[^\s@]+@[^\s@]+\.[^\s@]+$/, 'البريد الإلكتروني غير صالح'],
      index: true,
    },
    submittedByName: { type: String, trim: true },
    submittedByPhone: { type: String, trim: true },

    // ── Linkage to doctor_request ──────────────────────────────────────────
    linkedDoctorRequestId: {
      type: Schema.Types.ObjectId,
      ref: 'DoctorRequest',
      sparse: true,
      index: true,
    },

    // ── Review workflow ────────────────────────────────────────────────────
    status: {
      type: String,
      enum: REQUEST_STATUSES,
      default: 'pending',
      index: true,
    },
    reviewedAt: { type: Date },
    reviewedBy: {
      type: Schema.Types.ObjectId,
      ref: 'Admin',
    },
    rejectionReason: {
      type: String,
      enum: REJECTION_REASONS,
    },
    rejectionDetails: { type: String, trim: true, maxlength: 1000 },

    // ── Set after approval ─────────────────────────────────────────────────
    createdFacilityId: {
      type: Schema.Types.ObjectId,
      // refPath dynamically points to either 'Pharmacy' or 'Laboratory'
      refPath: 'createdFacilityModel',
    },
    createdFacilityModel: {
      type: String,
      enum: ['Pharmacy', 'Laboratory'],
    },

    // ── Notes ──────────────────────────────────────────────────────────────
    notes: { type: String, trim: true, maxlength: 2000 },
  },
  {
    timestamps: true, // adds createdAt + updatedAt
    collection: 'facility_requests',
  },
);

// ── Compound indexes ────────────────────────────────────────────────────────
FacilityRequestSchema.index({ facilityType: 1, status: 1, createdAt: -1 });
FacilityRequestSchema.index({ status: 1, createdAt: -1 });

// ── Statics ─────────────────────────────────────────────────────────────────
/**
 * Generate a unique request number: FREQ-YYYYMMDD-XXXXX
 * Called by the controller before inserting.
 */
FacilityRequestSchema.statics.generateRequestNumber = function () {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const random = Math.random().toString(36).slice(2, 7).toUpperCase();
  return `FREQ-${year}${month}${day}-${random}`;
};

// ── Virtual: matching specific-type label in Arabic for the dashboard ───────
FacilityRequestSchema.virtual('facilityTypeArabic').get(function () {
  if (this.facilityType === 'pharmacy') return 'صيدلية';
  if (this.facilityType === 'laboratory') return 'مختبر';
  return this.facilityType;
});

FacilityRequestSchema.set('toJSON', { virtuals: true });
FacilityRequestSchema.set('toObject', { virtuals: true });

// ── Export ──────────────────────────────────────────────────────────────────
module.exports = mongoose.model('FacilityRequest', FacilityRequestSchema);
module.exports.PHARMACY_SUB_TYPES = PHARMACY_SUB_TYPES;
module.exports.LAB_SUB_TYPES = LAB_SUB_TYPES;
module.exports.GOVERNORATES = GOVERNORATES;
